default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  # host: localhost

development:
  <<: *default
  database: kramituha_development
  encoding: utf8
  adapter: mysql2
  pool: 5
  username: root
  password:
  # socket: /tmp/mysql.sock

test:
  <<: *default
  database: kramituha_test

production:
  <<: *default
  database: kramituha_production
  username: kramituha
  password: <%= ENV['KRAMITUHA_DATABASE_PASSWORD'] %>
